---
name: Tests runner
on:
  pull_request:

jobs:
  tests:
    name: JS tests
    runs-on: ubuntu-latest
    env:
      ALCHEMY_TOKEN: not-so-secret-token

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Generate typechain
        env:
          SKIP_TYPECHAIN: true
        run: pnpm exec hardhat typechain

      - name: Run unit tests
        run: pnpm run test
