---
name: Tests runner

on:
  pull_request:

jobs:
  tests:
    name: JS tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install node
        uses: actions/setup-node@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm run test
